modLoader="javafml" #mandatory
loaderVersion="${loaderVersionRange}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="${libID}"
version="${libVersion}"
displayName="${libName}"
authors="${authors}"
description='''The core library for mods created by NotWhiteRice'''

[[mods]] #mandatory
modId="circuitsmod"
version="0.1.0-alpha"
displayName="Circuits"
authors="${authors}"
description='''A redstone expansion mod for Minecraft 1.21'''

[[mods]] #mandatory
modId="bountifulharvest"
version="0.1.0-alpha"
displayName="Bountiful Harvest"
authors="${authors}"
description='''A food mod made for Minecraft 1.21'''

[[dependencies.nwrcorelib]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.nwrcorelib]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.circuitsmod]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.circuitsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.circuitsmod]]
    modId="${libID}"
    mandatory=true
    versionRange="[0.1.0-alpha,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.bountifulharvest]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.bountifulharvest]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.bountifulharvest]]
    modId="${libID}"
    mandatory=true
    versionRange="[0.1.0-alpha,)"
    ordering="BEFORE"
    side="BOTH"

