modLoader="javafml" #mandatory
loaderVersion="${loaderVersionRange}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="${modID}"
version="${modVersion}"
displayName="${modName}"
authors="${authors}"
description="${modDesc}"

[[dependencies.${modID}]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modID}]]
    modId="minecraft"
    mandatory=true
    versionRange="${mcVersionRange}"
    ordering="NONE"
    side="BOTH"